export enum OrderStatus {
  SCHEDULED = 'SCHEDULED',
  ON_HOLD = 'ON_HOLD',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  WARRANTY = 'WARRANTY',
  DELAYED = 'DELAYED',
  DELIVERED = 'DELIVERED',
  ARCHIVED = 'ARCHIVED',
  CANCELLED = 'CANCELLED',
}
